version: '3.0'
services:
  redis:
    restart: always
    image: redis:alpine
    volumes:
      - ./data/redis:/data
  web: &mastodon
    restart: always
    image: ${MASTODON_IMAGE:-tootsuite/mastodon:edge}
    env_file: .env.production
    command: ./bin/rails s -p 3000 --early-hints
    depends_on:
      - redis
    extra_hosts:
      - storage.omanko.porn:192.168.0.12
    volumes:
      - ./config/mastodon/initializers/deflater.rb:/mastodon/config/initializers/deflater.rb
      - assets:/mastodon/public/assets
      - packs:/mastodon/public/packs
  streaming:
    <<: *mastodon
    command: yarn start
  sidekiq_default:
    <<: *mastodon
    command: bundle exec sidekiq -c 10 -q default
  sidekiq_push_and_pull:
    <<: *mastodon
    command: bundle exec sidekiq -c 20 -q push -q pull
  sidekiq_mailers:
    <<: *mastodon
    command: bundle exec sidekiq -c 1 -q mailers
  front:
    restart: always
    image: ykzts/h2o:2.2.5
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
      - streaming
    volumes:
      - ./data/letsencrypt:/etc/letsencrypt:ro
      - ./config/h2o:/etc/h2o:ro
      - ./public:/var/www/html:ro
      - assets:/var/www/html/assets:ro
      - packs:/var/www/html/packs:ro
volumes:
  assets:
  packs:
