version: '3.0'
services:
  statsd:
    image: datadog/docker-dd-agent:latest
    env_file: .env.datadog
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
  db:
    image: postgres:9-alpine
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    volumes:
      - ./data/redis:/data
  storage:
    image: minio/minio:latest
    ports:
      - "127.0.0.1:9000:9000"
    command: server /export
    volumes:
      - ./data/minio:/export
      - ./config/minio:/root/.minio
  web: &mastodon
    restart: always
    image: ${MASTODON_IMAGE:-gargron/mastodon:latest}
    env_file: .env.production
    command: ./bin/rails s -p 3000
    depends_on:
      - db
      - redis
      - storage
    volumes:
      - ./public/assets:/mastodon/public/assets
      - ./public/packs:/mastodon/public/packs
      - ./config/mastodon/initializers/deflater.rb:/mastodon/config/initializers/deflater.rb
  streaming:
    <<: *mastodon
    command: yarn start
  sidekiq:
    <<: *mastodon
    command: ./bin/bundle exec sidekiq
  webp-proxy:
    image: ykzts/webp-proxy:edge
    command: go-wrapper run -port 8080 -upstream-url http://storage:9000
    depends_on:
      - storage
  cache:
    image: nginx:alpine
    ports:
      - "127.0.0.1:10080:10080"
    depends_on:
      - webp-proxy
    volumes:
      - ./config/nginx:/etc/nginx:ro
  front:
    image: ykzts/h2o:2.2.3p1
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
      - streaming
      - cache
    volumes:
      - ./data/letsencrypt:/etc/letsencrypt:ro
      - ./config/h2o:/etc/h2o:ro
      - ./public:/var/www/html:ro
